Make sync process compatible with Bazel 6.0.0
It was reported that the plugin sync operation is not compatible with Bazel 6.0.0 because the aspect repository override results in the following error:
```
ERROR: Unable to find package for @[unknown repo 'intellij_aspect' requested from @]//:intellij_info_bundled.bzl: The repository '@[unknown repo 'intellij_aspect' requested from @]' could not be resolved: Repository '@intellij_aspect' is not visible from repository '@'.
```

This CL applies the fix recommened by the Bazel team in https://github.com/bazelbuild/intellij/issues/4067#issuecomment-1301833150

(cherry picked from commit 48820e5fa4cc57f1ea607b845e5cba1854adf361)