Amend #api251 marker to #api250 It turned out #api251 Intellij already has BuildToolModuleHandler
If v251 shim do not implement BuildToolModuleHandler, an runtime would be thrown

com.intellij.diagnostic.PluginException: Extension com.google.idea.blaze.scala.BlazeScalaBuildToolModuleHandler does not implement interface
  org.jetbrains.sbt.project.BuildToolModuleHandler
  (adapter=SimpleConstructorInjectionAdapter(implementation=com.google.idea.blaze.scala.BlazeScalaBuildToolModuleHandler, plugin=PluginDescriptor(name=Bazel for
  IntelliJ, id=com.google.idea.bazel.ijwb, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/IntelliJIdea2025.1/plugins/ijwb,
  version=9999-api-version-251, package=null, isBundled=false)))
      at com.intellij.serviceContainer.ComponentManagerImpl.createError(ComponentManagerImpl.kt:989)
      at com.intellij.openapi.extensions.impl.ExtensionPointImpl.checkExtensionType(ExtensionPointImpl.kt:210)
      at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapter(ExtensionPointImpl.kt:428)
      at com.intellij.openapi.extensions.impl.ExtensionPointImpl.createExtensionInstances(ExtensionPointImpl.kt:377)
      at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensionList(ExtensionPointImpl.kt:223)
      at com.intellij.openapi.extensions.ExtensionPointName.getExtensionList(ExtensionPointName.kt:54)
      at org.jetbrains.sbt.project.BuildToolModuleHandler.isHandledByBuildTool(BuildToolModuleHandler.java:15)
      at org.jetbrains.sbt.project.SbtProjectUtil$.isHandledByOtherBuildTool(SbtProjectUtil.scala:34)
      at org.jetbrains.sbt.project.SbtProjectUtil$.isInSbtProject(SbtProjectUtil.scala:29)
      at org.jetbrains.sbt.project.SbtProjectImportStateService.isImported(SbtProjectImportStateService.scala:31)
      at org.jetbrains.sbt.codeInsight.daemon.SbtProjectImportStateProblemHighlightFilter.shouldHighlight(SbtProjectImportStateProblemHighlightFilter.scala:23)/